# Generated by Django 4.2.28 on 2026-02-06 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BRDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('executive_summary', models.TextField(blank=True)),
                ('business_objectives', models.TextField(blank=True)),
                ('stakeholder_analysis', models.TextField(blank=True)),
                ('functional_requirements', models.TextField(blank=True)),
                ('non_functional_requirements', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('success_metrics', models.TextField(blank=True)),
                ('timeline', models.TextField(blank=True)),
                ('conflict_analysis', models.TextField(blank=True)),
                ('traceability_matrix', models.TextField(default='{}')),
                ('sentiment_analysis', models.TextField(default='{}')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('meeting', 'Meeting Transcript'), ('document', 'Document Upload')], max_length=20)),
                ('source_identifier', models.CharField(max_length=500)),
                ('raw_content', models.TextField()),
                ('processed_content', models.TextField(blank=True)),
                ('metadata', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_relevant', models.BooleanField(default=True)),
                ('relevance_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('functional', 'Functional'), ('non_functional', 'Non-Functional'), ('business', 'Business'), ('technical', 'Technical')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('stakeholder', models.CharField(blank=True, max_length=255)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.datasource')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('edit_request', models.TextField()),
                ('previous_content', models.TextField()),
                ('new_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('brd_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='api.brddocument')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='api.project'),
        ),
        migrations.CreateModel(
            name='ConflictDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='api.project')),
                ('requirement1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict1', to='api.extractedrequirement')),
                ('requirement2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict2', to='api.extractedrequirement')),
            ],
        ),
        migrations.AddField(
            model_name='brddocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brd_documents', to='api.project'),
        ),
    ]
